version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: weekly
    labels:
      - dependencies
